### PR TITLE
chrono: Add support for NaiveDate

### PR DESCRIPTION
**Pull request by TrackerSB**

### CODE REVIEW

**Comment by shekohex** [comment]
CI needs fixes.

**Comment by shekohex** [comment]
Looks like you need to run cargo fmt over the code.

**Review by shekohex — APPROVED** [review]
LG!

Thank you for adding this feature.

**Comment by TrackerSB** [comment]
What's the procedure of integrating the PR?

**Comment by shekohex** [comment]
> What's the procedure of integrating the PR?

I will publish a new package version very soon.

**Pull request merged**
